### ISSUE TITLE
Important CNV missing from *.cnv.txt in multi-sample data

### ISSUE THREAD

**Issue by aleighgreen** [morrislab/phylowgs#101]
Trying to run on multi-sample data, same tumor over multiple time points. 

This particular tumor developed an amplification in the later time point, which I am interested in tracking, however, when I run the data through the parser, the produced *cnv.txt file no longer contains that CNV.

Subset from the parsed cnv files:

Sample 1:

|chromosome | start | end | copy_number | minor_cn | major_cn | cellular_prevalence|
|--------------|------|-----|--------------|----------|----------|-----------|
|7 | 21827000 | 47933600 | 7 | 2 | 5 | 0.59324606|
|7 | 47942100 | 55714000 | 8 | 2 | 6 | 0.59324606|
|7 | 55750500 | 57701700 | 6 | 1 | 5 | 0.59324606|

Sample 2:

|chromosome | start | end | copy_number | minor_cn | major_cn | cellular_prevalence|
|--------------|------|-----|--------------|----------|----------|-----------|
|7 | 49815500 | 53930800 | 7 | 2 | 5 | 0.50245597|
|7 | 54610500 | 55629723 | 91 | 2 | 89 | 0.50245597|
|7 | 55713900 | 57187700 | 5 | 1 | 4 | 0.50313873|
|7 | 57188100 | 159025800 | 3 | 0 | 3 | 0.33803083|

Output of create_phylowgs_input.py *cnv.txt

|cnv | a | d | ssms | physical_cnvs|
|----|--|--|----|----|
|c61 | 375,603,431,292 | 534,000,576,000 |   | chrom=7,start=193200,end=7106600,major_cn=4,minor_cn=2,cell_prev=0.59324605519\|0.502455965617|
|c99 | 473,074,478,647 | 534,000,576,000 | s92,0,3;s93,0,3;s94,0,3;s95,0,3;s96,0,3 | chrom=7,start=95799300,end=102318900,major_cn=3,minor_cn=0,cell_prev=0.228184298411\|0.338030831561|
|c100 | 251,576,254,539 | 283,976,306,311 |   | chrom=7,start=156746700,end=159025800,major_cn=3,minor_cn=0,cell_prev=0.228184298411\|0.338030831561|

**Comment by sahilseth** [comment]
+1

**Comment by underbais** [comment]
Same issue here, major cnvs missing from cnv_data.txt. @aleighgreen, have you been able to resolve this? Thanks

**Comment by aleighgreen** [comment]
The reason has to do more with the inherent assumptions of how cnvs work in pwgs, cnvs are modeled as SSM, if you use the infinite sites assumptions, then no mutation with happen in the same place twice. We got around this by basically doing manual phylogeny construction with the assistance of PWGS. In the future, I wouldn't do it again tbh, it's a good software but this assumption is kind of problematic. Try Canopy maybe?

**Comment by underbais** [comment]
Hi Anna! Thanks for your comment. This is a major issue. Canopy has its own limitations too though
