### ISSUE TITLE
Automating tree extraction and plotting

### ISSUE THREAD

**Issue by underbais** [morrislab/phylowgs#109]
Hello devs,

I wonder if you would have any comments/thoughts on a possible python pipeline for automated best tree (a first few) extraction and plotting along with CCF info. I mean js/browser implementation is great but not really automation-friendly.

Any advise?

Thanks!

**Comment by aleighgreen** [comment]
For what's it worth, if you check out the snakemake pipeline for PWGs that I have, I've got a pretty scrappy script that sort of does this....the whole thing was written for the NIH biowulf cluster as well, so you might be able to adapt it to your needs.  https://github.com/aleighgreen/pwgs_snakemake/blob/master/parse_pwgs_output.py

**Comment by underbais** [comment]
Awesome, thank you for sharing! I kind of did the same in R but will definitely check this out
