### ISSUE TITLE
Question: Performance with exome sequencing?

### ISSUE THREAD

**Issue by armish** [morrislab/phylowgs#12]
I know that you specifically focus on WGS; but do you have any suggestions or objections for using this framework on WES instead WGS? If I do run PhyloWGS on WES data, are there obvious biases that I should be aware of?

**Comment by AmitDeshwar** [comment]
Just looking at SNVs, there's no difference when using WES data, in fact the greater depth leads to more accurate reconstruction.  If you look at our phyloSub paper we performed accurate reconstruction using only a handful of variants that had been deep sequenced, WES lies along the same continuum. 
The main issue is that calling CNVs is harder with WES data.  I think that the best results come from using CNV calls from array CGH and WES to identify the SNVs but we haven't extensively explored this.

**Comment by armish** [comment]
Thanks @AmitDeshwar! We will predominantly run it on WES and sometimes WGS (and rarely together with CGH). Just wanted to make sure I don't miss anything obvious.
