### ISSUE TITLE
Question: Best way to contribute?

### ISSUE THREAD

**Issue by armish** [morrislab/phylowgs#14]
Do you guys prefer me sending atomic PRs (for simple improvements/clarifications) your way or should I simply work on a fork on my own and let you know about the final state? 

The context for this is mentioned in #13 as to be able to make this part of our pipeline (https://github.com/hammerlab/cycledash), I need to change a few things.

**Comment by quaidmorris** [comment]
People have been contributing in both ways so far.

**Comment by jwintersinger** [comment]
Hi Armish,

If you make simple improvements/clarifications that are generally applicable to PhyloWGS rather than being specific to your pipeline, please free to make a PR so we can merge your modifications into master in a timely fashion.

Thanks!

**Comment by armish** [comment]
Perfect -- thanks for conforming this!
