### ISSUE TITLE
Add unit tests and enable continuous integration/testing

### ISSUE THREAD

**Issue by armish** [morrislab/phylowgs#15]
It is currently possible to follow the example outlined in the `README.md` file and take a look at the results, which is a manual (sanity) check on PhyloWGS's utility; but I would like to make sure, the things I will change won't break anything along the way. 

For this, it would be great if you can provide a few simple tests so that contributors (#14) can know when they introduce a bug in the framework. Even better would be to enable Travis integration, so that each PR can automatically be tested before your consideration.

**Comment by jwintersinger** [comment]
Hi @armish ,
Thanks for doing this, integrating your code is still on the TODO list.

**Comment by jwintersinger** [comment]
Hi @armish,
We don't have the resources to do this now but @quaidmorris is talking about hiring an engineer to make these (and other) changes. Please say tuned.
