### ISSUE TITLE
List requirements in a `requirements.txt` file

### ISSUE THREAD

**Issue by armish** [morrislab/phylowgs#16]
Currently users are advised to install `scipy`, `numpy` and `ete2` via pip before using PhyloWGS; but it would make things easier if you list these requirements (together with the preferred versions of these) in a `requirements.txt` file, so that users can simply do a `pip install -r requirements.txt` and don't worry about the incompatibility across libraries.

This also relates to #15 and would be good for reproducibility.

**Comment by quaidmorris** [comment]
Thanks for the tip!

Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.med.utoronto.ca
cell:  (416) 220 5796

**Comment by jwintersinger** [comment]
Thanks, Armish! I added a `requirements.txt`. PhyloWGS should work with the latest stable versions of these libraries, so I haven't specified precise version requirements.

**Comment by armish** [comment]
Thanks so much Jeff!

**Comment by AmitDeshwar** [comment]
Do we still need eta2?
