### ISSUE TITLE
Estimating % of cells containing a CNV

### ISSUE THREAD

**Issue by medlste** [morrislab/phylowgs#18]
Hi,

I have exome and whole genome sequencing from the same samples. Can you recommend a programme for predicting the % of cells containing a CNV so I can input a and d appropriately in the cnv_data.txt file? 

Thanks

**Comment by medlste** [comment]
I'm just wondering: would it be sufficient to put a as the normalised* read depth for the CNV in question in the germline and d as the normalised* depth in tumour (*normlaised by total number of reads aligned in each sample, respectively)?

**Comment by AmitDeshwar** [comment]
Hi,
We recommend using either Battenberg or TITAN to do subclonal CNV calling.  They both need WGS sequencing data as input.

**Comment by medlste** [comment]
Thanks
