### ISSUE TITLE
Question: How to run PhyloWGS jointly on multiple samples?

### ISSUE THREAD

**Issue by armish** [morrislab/phylowgs#21]
Looks like the CLL example in the PhyloWGS paper was the result of a multi-sample run and you do explain the possibility of extending the method for multiple-sample analysis; but what exactly is needed for this? The SSM data doesn't encode for patient ID and your README file doesn't have any guidelines on how to evolve models in a multi-sample manner -- so I am a little bit lost on this one. Is there any documentation on this feature or on how to replicate the CLL analysis in your paper (so that I can use that as a see-by-example tutorial for myself)?

Thanks!
-- Arman

**Comment by armish** [comment]
Sorry to insist, but I just wanted to make sure this is still on your radar. Any pointers will be much appreciated ;)

**Comment by AmitDeshwar** [comment]
Hi Arman

By multi-sample we mean multiple samples taken from the same patient.
The input data is encoded in the input files where in the a and d columns
have multiple entries separated by a comma, where each entry represents the
a/d for a particular sample.  The ssm_data.txt and cnv_data.txt available
on the github repo demonstrates this.

Amit

**Comment by armish** [comment]
Thanks @AmitDeshwar! Does the order of the samples need to be same throughout the file and how do you encode the lack of a mutation in a particular sample?

**Comment by AmitDeshwar** [comment]
Yes the order needs to be the same for each mutation.
There's always a a and d value for the mutated locus even if it is not
present in the sample (a=d in that case).
If that information is not available you have to approximate the value by
some means such as averaging the read depth at the other samples.

**Comment by armish** [comment]
I see — I was hoping to **parse** multiple VCFs/SSMs representing different samples and combine them into a single SSM, but looks like this will require some more work and going back to the BAM files to extract the coverage for the variant region from all samples. 

Thanks again. Will probably implement imputation-by-average and combine-SSMs features and send you guys a PR with some documentation.

-- Arman

**Comment by hxrts** [comment]
@armish did you end up creating a solution for this. I'm at the same point, would prefer not to construct a combined VCF if necessary. Thx!

**Comment by armish** [comment]
@hxrts: yeah -- but it was a custom solution that might need some tweaking to make it work yourself. In our case what I ended up doing was 

1. Converting sample VCFs into SSMs individually using [PhyloWGS's internal parse script](https://github.com/morrislab/phylowgs/blob/master/parser/create_phylowgs_inputs.py)
2. Find variants that exist in some samples but not others and go back to the BAM files to fill in normal read counts in these SSMs via [samtools](http://www.htslib.org/) (so that all SMM files have the same exact number of lines in them)
3. Merge these filled-in SSMs into single ones using this relatively simple bash script: https://gist.github.com/armish/a065b81979b60089de37#file-merge_ssms-sh-L13-L21 (it has a few custom folder paths but the meat is the highlighted ones)

Not the brightest solution, but dependency on the BAM files to extract information for missing variants was a deal breaker for me and was the reason I ended up creating a bunch of custom script to get to this one at a time.

Hope this helps!

**Comment by hxrts** [comment]
@armish Thanks so much for the reply armish. I'm most of the way through a similar solution, but this is still very helpful. In the end, we're using mostly whole exome data so the effort may be somewhat needless, however I'd like some kind of orthogonal validation of a PyClone clustering result.

**Comment by armish** [comment]
no problem at all, @hxrts -- glad if that was helpful. 

_Re: exome sequencing_: we also work with WES data quite a lot and one of my earliest questions to the team was related to this (in case you missed it): https://github.com/morrislab/phylowgs/issues/12

**Comment by hxrts** [comment]
@armish you just preempted my question to the phyloWGS authors, so so helpful. thanks!

**Comment by jungminchoi** [comment]
Hi Amit,
Could you kindly share what your planned timeline is to release the ssm parser to handle multiple samples from the same patient? 
Thanks!
Jungmin

**Comment by jwintersinger** [comment]
Hi @jungminchoi 
It's still on the TODO list. It's relatively I'll let you know when it's done. Does anyone know if there is a multi-sample VCF standard? I'd hate to invent a new file format.

**Comment by timodonnell** [comment]
@jwintersinger Yes, the VCF standard supports multiple samples. Each sample gets its own column in the VCF. The VCF at the top of this [page](http://www.1000genomes.org/wiki/Analysis/vcf4.0) gives a simple example. 

In case having some data would help with this, I have read counts (num variant reads, num reference reads) for about a dozen ovarian cancer patients, where for each patient we have 2-4 samples. We also have CNVs. We would love to get phylowgs analyses for these patients. (Our data is just in a big csv file though not in a VCF.) Please feel free to get in touch if this dataset would help at all and I can share it with you. Thanks for your work on phylowgs!

**Comment by callosciurus** [comment]
@jwintersinger Could you elaborate on the definition of cnvs in the input data for multiple sample runs? 

Looking at the example input file shown below, it seems like there are 5 samples, and a and d are specified for each one of them. Mutations s2 and s4 then appear to have the same CNs in each of the five samples, correct? But what if CNs differ between the five samples? Say s2 has CN status of 1,2 in sample 1, CN 0,1 in sample 2, and CN 1,1 in the remaining samples. How would I specify that?

More generally, why do s2 and s4 have different copy numbers (1,2 vs 0,1) but are part of the same cnv (c0)?

As others have pointed out, great tool, and thanks for your help!


cnv	a	d	ssms
c0	66023,50883,62757,36056,58777	126755,100469,121941,71263,115417	s2,1,2;s4,0,1

**Comment by quaidmorris** [comment]
@callosciurus: @jwintersinger asked me to answer your questions.

First, to answer your question: 

[I'm using CNAs rather than CNVs because Peter Van Loo has corrected my terminology]

> More generally, why do s2 and s4 have different copy numbers (1,2 vs 0,1) but are part of the same cnv (c0)?

Here, c0 is a merged CNAs consisting of two different, non-overlapping CNAs. Merged CNAs are groups of non-overlapping CNAs that share the same a,d values but can have different copy numbers. We indicate the copy numbers for each SSM based on which of the original CNAs they are in. Jeff's parser creates these merged CNAs out of the all of the clonal CNAs. This simplifies the inference for PhyloWGS because it only needs to place one merged clonal CNA in the tree rather than assigning each clonal CNA independently. We don't currently merge subclonal CNAs in the parser but you could do this yourself if you are using a method like TITAN, Theta, or cloneHD that groups CNAs into subclonal lineages.

Re: overlapping CNAs

If you have a region that has CN 1,2 in one sample and CN 0,1 in another, you would indicate that as two separate CNAs, i.e. two different entries in the CNA file. It's ok to have overlapping CNAs as multiple lines in the cna_data.txt file. You do need to make sure to add the SSMs potentially affected by the CNAs to each of the independent lines. So, say SSMs s0 and s1 are affected in this circumstance then your cna_data.txt file would look something like:

c1 70,200 120,200 s0,1,2;s1,1,2
c2 100,40 100,60 s0,0,1;s1,0,1

Here I've set a=d for c2 in sample 1 which implies that no cells have c2 in this sample. Similarly a=d for c1 in sample 2. However, you can permit these two subclonal CNAs states to co-exist in the population in the two samples by setting these values differently.

**Comment by quaidmorris** [comment]
@timodonnell Thanks for the pointer to the VCF and the offer of data!

We have ample data to test drive multiple sample PhyloWGS CNAs on. Jeff just needs some time to implement it.

Jeff and I worked out some of the issues today but we have to make some changes in how we estimate a and d values for CNAs. I think we'll implement them first on a fork because of the required changes to the a and d values will affect all of PhyloWGS.

**Comment by lihang598602** [comment]
@quaidmorris,
I had some problem with the multi-sample CNA input data.
In case,for neutral copy number, how to give the "a" and "d" value? a=100,d=100 or a=200,d=200,do they have the same impact?

**Comment by quaidmorris** [comment]
@lihang598602 
According to @jwintersinger, the parser ignores the a & d values for neutral copy number. So, it shouldn't matter what you put it. Hopefully he can confirm.

Also, @jwintersinger, does the parser recognize that a haploid X is normal copy number in males?

**Comment by jwintersinger** [comment]
@lihang598602: @quaidmorris is right in saying that we ignore neutral-CN in single samples However, I understand you're asking about multisample, which is more difficult. Your intuition is correct that you should have `a = d` in such cases, but the question is how to establish sensible `d` values for a region when it's normal in one sample but abnormal in another. Having `a = d = 100` and `a = d = 200` is *not* equivalent -- the higher `d` is, the more confidence the model has in the observation, meaning that the given CNV event will have more weight on the cellular prevalence inferred for the associated population, and that it will be "harder" to move the CNV between nodes between successive phylogeny samples.

We're working on this right now, with the details of our algorithm being roughly thus:

```
1. Take intersection of all regions
  If *any* sample lacks data for a region, we can't calculate meaningful `a` or `d` values for it in that sample, so don't use that region at all
2. Take union of breakpoints
  Now we have values for every region, for every sample, with identical breakpoints in each
3. For each region `R`:
  If `R` is (1, 1) in each sample, then ignore
  If one or more samples have `R` as (m, n), with the rest (1, 1):
    Calculate `a` and `d` for each sample. `d` is affected by the following things:
      Region length (same across samples)
      Read depth (which we infer from mean variant RD in VCFs -- may differ between samples)
      Read length (technically may differ between samples, but let's just assume it's constant)
      Delta CN (same for all aberrant samples; if sample is normal, then it's fixed to 1 so the math works okay)
    `a` is affected by the cellular prevalence for each sample
  If one or more samples have `R` as aberrant, but with different (major, minor): discard region
```

I'll reply to this issue again once we have the above implemented.

@quaidmorris, we currently ignore SSMs on sex chromosomes, and we don't properly account for haploid state in determining `d` for CNVs. I'll talk to you on Slack about how we should fix this.

**Comment by quaidmorris** [comment]
So folks, @jwintersinger added support for multisample CNAs. Please give it a try.
