### ISSUE TITLE
how to create JSON files

### ISSUE THREAD

**Issue by zhaohao76** [morrislab/phylowgs#23]
Hi,
Thanks for contributing the phylowgs tool!

I set up PhyloWGS and run it using the test data. I could went through Step3 by running:
python2 evolve.py ssm_data.txt cnv_data.txt. A few files were created, such as top_k_trees, trees.zip. However, I do not know in Step 4, what "example_data" means. How can I run step 4 following Step 3's result? More details in the instruction will be greatly appreciated!
Tony

**Comment by jwintersinger** [comment]
Hi @zhaohao76,

Sorry for the delay in my response. "example_data" can be any string -- it's just a name that identifies your results. We typically use the GUIDs that were assigned to our tumors when they were sequenced.

Please let us know if you have other questions!
