### ISSUE TITLE
How to interpret the output

### ISSUE THREAD

**Issue by mofanhz** [morrislab/phylowgs#24]
I was wondering how can I get the details of mutations that were used to estimate population of each subclone. 
For example
clone1=s1+s2+s3; 
clone2=s1+s2+s3+s4; 
clone3=s1+s2+s3+s4+s5; 
clone4=s1+s2+s3+s4+s6

Thanks,

**Comment by jwintersinger** [comment]
Hi @mofanhz,

If you follow step 4 in the [README](https://github.com/morrislab/phylowgs/blob/master/README.md) ("Generate JSON"), the mutation assignment information will be in the `example_data.mutass.zip` file that is created. It will be a zip file containing JSON files listing mutation assignments for each tree sampled by PhyloWGS.

Please let us know if you have other questions!
