### ISSUE TITLE
CNV_data format

### ISSUE THREAD

**Issue by zhaohao76** [morrislab/phylowgs#27]
Hi,
I have 2 questions about the format of CNV data.
1)column a, "number of reference reads covering the CNV", what are "reference reads"? Similarly, what are "total number of reads covering the CNV" in column d?

2) in the example cnv_data.txt, column a has a few comma separated numbers--is this expected to be one integer?

Thank you!

**Comment by jwintersinger** [comment]
I think this question is answered in the readme.
