### ISSUE TITLE
CNV Calls

### ISSUE THREAD

**Issue by esantosh1** [morrislab/phylowgs#28]
Hi,

Could you please let me know if there are any alternatives to Battenberg/Titan for CNV Calls and MuTect for SSM ?

Thanks.

**Comment by quaidmorris** [comment]
Alternatives for what? Using PhyloWGS or accomplishing the goals of these
methods?

Q

On Friday, February 5, 2016, esantosh1 <notifications@github.com> wrote:

> Hi,
>
> Could you please let me know if there are any alternatives to
> Battenberg/Titan for CNV Calls and MuTect for SSM ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/morrislab/phylowgs/issues/28>.
>


-- 
Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.med.utoronto.ca
cell:  (416) 220 5796

**Comment by esantosh1** [comment]
Hi,
I would like to generate the SSM and CNV inputs for phyloWGS. As mentioned in README, the CNV calls from Battenberg or TITAN is supported. However, when I am trying to get the CNV calls from Battenberg and the script takes a long time on a real dataset. I was looking out an alternative for accomplishing the goals of these methods as inputs to phyloWGS?

**Comment by quaidmorris** [comment]
You could try Absolute but you wouldn't get subclonal CNA calls and you
might have to parse the CNA output yourself.

Best,
Quaid

On Friday, February 5, 2016, esantosh1 <notifications@github.com> wrote:

> Hi,
> I would like to generate the SSM and CNV inputs for phyloWGS. As mentioned
> in README, the CNV calls from Battenberg or TITAN is supported. However,
> when I am trying to get the CNV calls from Battenberg and the script takes
> a long time on a real dataset. I was looking out an alternative for
> accomplishing the goals of these methods as inputs to phyloWGS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/morrislab/phylowgs/issues/28#issuecomment-180218300>.
>


-- 
Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.med.utoronto.ca
cell:  (416) 220 5796
