### ISSUE TITLE
Lack of output

### ISSUE THREAD

**Issue by rschenck** [morrislab/phylowgs#30]
Hello,

I've ran this tool on a few samples now (phylosub version, i.e. passing empty CNV file). The example dataset generated expected results.

My input files have somewhere between 200-600 SSMs. I have 2-3 exomes per sample. They exhibit varied heterogeneity.

Sample input:
id	gene	a	d	mu_r	mu_v
s0	line3	20,7	13,4	0.999	0.499
s1	line6	77,45	8,11	0.999	0.499
s2	line7	119,86	6,10	0.999	0.499
s3	line8	118,43	8,43	0.999	0.499
s4	line10	58,43	58,6	0.999	0.499
s5	line12	111,84	9,10	0.999	0.499

For samples with 0 observed variants I took the mean reads and set that for both a and d as instructed.

What I observe while running 'evolve.py' is a constant stream of 'Splice sampler shrank down. Keep current state.'

The final results in witness when I visualize and verify with checking the but_assignments in the mutass.json file is everything belonging to "1". There are no variant allele frequencies in the plot either.

Any help or suggestions would be appreciated. I would like to know if there's something that I'm doing incorrectly or if there truly is no phylogenetic inferences that can be drawn from my data.

Cheers

**Comment by jwintersinger** [comment]
Hi Ryan,

The problem is your `a` and `d` values. `a` should be the number of reference reads, while `d` should be the total number of reads. (Thus, `d - a` is the number of variant reads.)

Please let me know if you have any other questions!

**Comment by rschenck** [comment]
This is excellent. Worked like a charm, not sure how I overlooked that. Thank you.

Cheers
