### ISSUE TITLE
RuntimeWarning using write_results.py

### ISSUE THREAD

**Issue by ShadrielleE** [morrislab/phylowgs#39]
I would like to bring up this warning when running write_results.py:
/oicr/x86_64/boutroslab/sw/phylowgs/1.1/bin/pwgsresults/result_munger.py:146: RuntimeWarning: invalid value encountered in double_scalars
  implied_phi = 2 \* (total_reads - ref_reads) / total_reads

However, although it still generates all the JSON files, should we be worried if the results are truncated or some trees are missing? This happened in almost 25% of the samples we ran, and not necessarily because they have too many SSMs or CNVs. Moreover, when viewing the results using the tree viewer, the "best" tree associated with some of these samples have really low LLH values (e.g. -18000, but still the largest LLH among the trees). Should we be concerned about this, and try rerunning?

Thanks
Shadrielle

**Comment by AmitDeshwar** [comment]
If this happens, it suggests that you might have zero's in your d column
which will result in invalid scores.
Have you checked for those?

**Comment by ShadrielleE** [comment]
Yes there are 0's in the d column. Alternatively, there are some cnvs that have a=0,d=1. We've gathered that these represent the CNVs reported by the CNA caller (in our case TITAN), that are 1-bp in length... However, there are some samples that didn't have the runtime issue but also had such values, so that may not be the cause of the issue. We'll try a few of the samples that failed and remove those cnvs with d=0 and d=1.

Thanks for the quick reply.

**Comment by quaidmorris** [comment]
@ShadrielleE,
I think you should filter out the 1-bp CNAs. That's a problem.

**Comment by ShadrielleE** [comment]
Okay we will do that. Thanks

**Comment by ShadrielleE** [comment]
Just a quick update on this. The RuntimeWarning goes away after we remove all lines where a=0 and d=0
