### ISSUE TITLE
Incorrect Calculations of CCF

### ISSUE THREAD

**Issue by ShadrielleE** [morrislab/phylowgs#42]
Hello,

I think there's a miscalculation in CCF here: (this is using the most recent cnv-int branch, ~June 20  2016)

![wrong-ccf](https://cloud.githubusercontent.com/assets/1753326/16813882/84cf7838-4901-11e6-861f-e5627f5c5adf.png)

I manually calculate CCF to be the following:
CCF(0) = 0
CCF(1) = 0.526
CCF(2) = 0.474
CCF(3) = 0.331
CCF(4) = 0.272

Could you double check if this is correct?
Thanks,
Shadrielle

**Comment by quaidmorris** [comment]
Hi @ShadrielleE,
Thanks for pointing this out. You are correct, the calculation of CCF is incorrect here. To compute CCF divide each population's cellular prevalence by the largest cellular prevalence. This clearly won't work for polyclonal tumours. We'll make the fix when we have the chance.

**Comment by ShadrielleE** [comment]
@quaidmorris 
Thanks Quaid. For polyclonal tumours, rather than divide each population's cellular prevalence by the largest cellular prevalence, we would divide it by the sum of the cellular prevalences of the clonal nodes. So
CCF(1) = 0.485 / (0.485 + 0.437) = 0.526

Hope that helps.

**Comment by quaidmorris** [comment]
Hi @ShadrielleE 
I agree, that is the correct solution. Any chance that you can make the change to the codebase?

**Comment by af8** [comment]
Hi @ShadrielleE 
Have you been able to modify the code to fix this ?
Thank you

**Comment by ShadrielleE** [comment]
@af8 
Sorry I had totally forgotten about this. But after looking at the code again, it does look like @jwintersinger already put a fix to this back in October 2016.
