### ISSUE TITLE
"! I can't find file `pgflibrarytikzfit.code.tex'" error when running initial tests

### ISSUE THREAD

**Issue by scottidanjah** [morrislab/phylowgs#5]
Hi,

I seem to be having an issue when running the initial tests for the phylowgs when using the evlove.py script on the ssm_data.txt and cnv_data.txt files. 

> ! I can't find file `pgflibrarytikzfit.code.tex'.
><argument> ...t pgflibrarytikz\pgf@temp .code.tex   
> \catcode `\@ =\csname tikz...  
>l.4 \usetikzlibrary{fit,positioning}  
                                    
>Please type another input file name  
>! Emergency stop.  
><argument> ...t pgflibrarytikz\pgf@temp .code.tex   
>                                                 \catcode `\@ =\csname tikz...  
>l.4 \usetikzlibrary{fit,positioning}  
>                                    
>*** (job aborted, file error in nonstop mode)

I suspect it might be because I'm using an older versions of pdfTeXk and the pgf and tikz packages:
* This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
* tikz.sty    2006/10/17 v1.10 (rcs-revision 1.68)
* pgf.sty    2006/10/11 v1.10 (rcs-revision 1.7)

Would updating these to newer versions help this issue, or is might it be something else?

**Comment by jwintersinger** [comment]
Hi Scott,

According to [this post](http://tex.stackexchange.com/questions/59663/i-cant-find-file-pgflibrarytikz-code-tex), updating the libraries should help. When running PhyloWGS, I use a "medium scheme install of [TeX Live](https://www.tug.org/texlive/quickinstall.html), which works well.

Incidentally, we're working on a new visualization system that will eliminate the dependency on LaTeX. We will likely release it in the next couple weeks.

Please let us know if we can be of any other help!

**Comment by scottidanjah** [comment]
Updating Tex Live solved the issue. Thank you!
