### ISSUE TITLE
Multi-sample mode

### ISSUE THREAD

**Issue by amcpherson** [morrislab/phylowgs#50]
Update the README with instructions on how to run phylowgs with multiple tumour samples.

**Comment by jwintersinger** [comment]
Thanks for the suggestion! I updated the [parser README](https://github.com/morrislab/phylowgs/tree/master/parser#multi-sample-mode) with a multisample example. As part of this, I overhauled how multiple samples are specified on the command line.

Does this make clear how to run with multiple samples?

**Comment by amcpherson** [comment]
Everything works and is clear but I just wanted to double check something.  If across the multiple samples there are more than two non-diploid copy number states for the same segment, that segments and contained SSMs are filtered?
