### ISSUE TITLE
Unable to creaate SSM_file.txt

### ISSUE THREAD

**Issue by surajmetha55** [morrislab/phylowgs#53]
I am trying to create ssm_file.txt using script create_phylowgs_inputs.py which is available inside parser folder.
The command I use is:  python create_phylowgs_inputs.py vcf_files sample1=mutect_tcga.vcf  --vcf-type sample1=mutect_tcga
 But it give me error as :  AssertionError: Must specify same number of VCF files and VCF types

**Comment by jwintersinger** [comment]
Hi @surajmetha55,

`vcf_files` should not be included on the command line. Try running with this instead:

` python create_phylowgs_inputs.py vcf_files sample1=mutect_tcga.vcf --vcf-type sample1=mutect_tcga`

Please let me know if this works!
