### ISSUE TITLE
Tree viewer in Witness is empty

### ISSUE THREAD

**Issue by SunDionel** [morrislab/phylowgs#55]
Hello,

I can see the contents under the Tree summaries tab but for the Tree viewer, I only see the column names "Index 	nlgLH 	Nodes 	Dist 	LI 	BI" on the right side.

In witness/data I have a test_results folder with the following:
NY.mutass.zip
NY.muts.json
NY.summ.json

This is the content of index.json in the data folder:
{"test_results": [{"muts_path": "data/test_results/NY.muts.json", "name": "NY", "summary_path": "data/test_results/NY.summ.json"}]}

**Comment by JenniferShelton** [comment]
My output is the same (top_k_trees shows trees however none show in the tree viewer window). Do you have any suggestions?

**Comment by SunDionel** [comment]
I've used a previous version of Witness, and it worked. The problem might be with one of the updates.

**Comment by JenniferShelton** [comment]
There is a bug I think (I'm running again to see). 

This line from phylowgs/parser/create_phylowgs_inputs.py

`D_max = int(np.round(avg_ssms_in_tumour * self._read_depth))`

tries to convert a numpy array with int()

**Comment by SunDionel** [comment]
I also had that problem so I took the max of `np.round(avg_ssms_in_tumour * self._read_depth)`
as suggested by the first poster here:
[Array length error when preparing files in a multi-samples setting #54](https://github.com/morrislab/phylowgs/issues/54)

**Comment by JenniferShelton** [comment]
Thanks,

I have multiple samples so I fixed it with map() but it looks like a bug fix went up 7 days ago that should cover this now too.

**Comment by SunDionel** [comment]
yes, thanks :)
