### ISSUE TITLE
phyloWGS fails on test dataset

### ISSUE THREAD

**Issue by davismcc** [morrislab/phylowgs#59]
Hi there,

phyloWGS looks like a great tool, but I'm having trouble getting it installed/working.

I am trying to install on a RedHat cluster with gcc 4.8.5, GSL 2.2.1 in a conda Python 2.7.12 environment with Numpy, Scipy, ETE2, etc installed.

Running the "compile" command (` g++ -o mh.o -O3 mh.cpp  util.cpp `gsl-config --cflags --libs`) runs without returning an error or any output.

Unfortunately, when I run the test command, I get the following error:
```
(py2) [davis@... phylowgs]$ python evolve.py ssm_data.txt cnv_data.txt
[2017-05-31 19:27:22.067044] Starting MCMC run...
[2017-05-31 19:27:22.069648] -1000
/nfs/software/stegle/users/davis/phylowgs/mh.o: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/nfs/software/stegle/users/davis/conda-envs/py2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/nfs/software/stegle/users/davis/conda-envs/py2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "evolve.py", line 348, in run
    tmp_dir=args.tmp_dir
  File "evolve.py", line 124, in start_new_run
    do_mcmc(state_manager, backup_manager, safe_to_exit, run_succeeded, config, state, tree_writer, codes, n_ssms, n_cnvs, NTPS, tmp_dir)
  File "evolve.py", line 195, in do_mcmc
    config['tmp_dir']
  File "/nfs/software/stegle/users/davis/phylowgs/params.py", line 61, in metropolis
    sp.check_call(['%s/mh.o' % script_dir, MH_ITR, MH_STD, N_SSM_DATA, N_CNV_DATA, NNODES, TREE_HEIGHT, FNAME_SSM_DATA, FNAME_CNV_DATA, FNAME_C_TREE, FNAME_C_DATA_STATES, FNAME_C_PARAMS,FNAME_C_MH_ARATIO, NTPS])
  File "/nfs/software/stegle/users/davis/conda-envs/py2/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/nfs/software/stegle/users/davis/phylowgs/mh.o', '5000', '100', '11', '1', '2', '2', 'ssm_data.txt', 'cnv_data.txt', '/tmp/pwgsdataexchange.N7sDQk/c_tree.txt', '/tmp/pwgsdataexchange.N7sDQk/c_data_states.txt', '/tmp/pwgsdataexchange.N7sDQk/c_params.txt', '/tmp/pwgsdataexchange.N7sDQk/c_mh_ar.txt', '5']' returned non-zero exit status 127

[2017-05-31 19:27:22.104864] Run failed.
```

Have you seen this sort of error before? Any help with debugging/troubleshooting to get phyloWGS working would be greatly appreciated!

Thanks is advance for your time,
Davis

**Comment by quaidmorris** [comment]
HI Davis,
It looks like you don't have the GNU Scientific Library installed.  You
need libgsl.so on your path.

Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.ca <http://morrislab.med.utoronto.ca>
cell:  (416) 220 5796

**Comment by davismcc** [comment]
Thanks for the reply!

GSL is installed (e.g. I can call gsl-config at the command line.)

Do you know off hand how I can check that libgsl.so is in my path/add it to the path?

Best
Davis

**Comment by quaidmorris** [comment]
Maybe this will help?

https://www.gnu.org/software/gsl/manual/html_node/Shared-Libraries.html

Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.ca <http://morrislab.med.utoronto.ca>
cell:  (416) 220 5796

**Comment by davismcc** [comment]
That really did help! 

I tracked down the shared libraries in my conda environment, added them to my LD_LIBRARY_PATH variable, and we're away. The test run succeeded, so looks like we're happy phyloWGS campers here now.

Thanks for your patience with the unix n00b question and very speedy respone!!
