### ISSUE TITLE
Undocumented output in working directory

### ISSUE THREAD

**Issue by davismcc** [morrislab/phylowgs#67]
Hi there

I just encountered some unexpected behaviour with `phyloWGS`. I am trying to pipeline analysis with a snakemake (http://snakemake.readthedocs.io/en/stable/) workflow, and trying to run `phyloWGS` on 16 different individuals. Snakemake runs from a head directory, and the SSM and CNV data are in sub-directories. 

I want the output from `phyloWGS` to appear in the relevant sub-directories for each individual.
e.g. command run by snakemake for a particulary individual:
```
/[...]/davis/conda-envs/py2/bin/python /[...]/davis/phylowgs/evolve.py --top-k-trees Data/exome-point-mutations/xuja/phyloWGS/xuja_top_k_trees.txt --clonal-freqs Data/exome-point-mutations/xuja/phyloWGS/xuja_clonal_freqs.txt --random-seed 31052017 --tmp-dir tmp Data/exome-point-mutations/xuja/phyloWGS/xuja_ssm_data.txt Data/exome-point-mutations/xuja/phyloWGS/xuja_cnv_data.txt
```

This (can) produce the output files `Data/exome-point-mutations/xuja/phyloWGS/xuja_top_k_trees.txt`, `Data/exome-point-mutations/xuja/phyloWGS/xuja_clonal_freqs.txt`, but also produces the (undocumented) following files in the *head* directory:
* `random_seed.txt`
* ` state.initial.pickle`
* `state.last.pickle`
* `trees.zip`

This seemed to be fine the first time I ran one of these jobs with snakemake in the head directory. The side-effect output files in the head directory served their function and the desired output (top trees, clone-freqs) were produced as desired.

However, when trying to run `phyloWGS` jobs for multiple individuals simultaneously with snakemake, they all seem to look at the side-effect output in the head directory. I think they try to "resume existing run", but that run (the first one that completed successfully) is already complete, so they do not generate results for the input data that they're meant to be looking at!

I can work around this in snakemake, but I think this is seriously undesirable behaviour: undocumented side-effect files produced in the working directory and on top of that silently resuming an existing run if any compatible run data is found in the working directory. I think this is very dangerous.

I would *strongly suggest* that (at least as an option) the user specifies an output *directory* and `random_seed.txt`, ` state.initial.pickle`, `state.last.pickle` and `trees.zip` are produced there. When resuming a run, the directory containing these output files could (should) be specified. In both cases, the directory could default to the current working directory, in which case current behaviour would not change.

Further feedback:
* there seems not to be a `--version` or similar flag available at the command line to tell the user what version of `phyloWGS` is being used
* the `-h` help flag is ignored if `phyloWGS`

Thanks a lot for the (overall) excellent method and software. Sincere apologies if any of the above is indeed covered in the documentation and I overlooked it.

Best wishes
Davis

PS: I am running this on a linux cluster (RHEL 7.0). I can't tell what version of `phyloWGS` I'm using, but I cloned the repository about 8 weeks ago.

**Comment by jwintersinger** [comment]
Hi Davis,

Thank you for your feedback! Is it possible to control what working directory is used via snakemake? If not, we can look at adding the option for controlling what directory it uses.

Thanks!
