### ISSUE TITLE
Error in Write_results.py, assertion error

### ISSUE THREAD

**Issue by dtm2117** [morrislab/phylowgs#68]
Hello,

I'm recently upgraded to the newest verison of phylowgs from cloning the master branch. I'm receiving this error: 

25 Superclone: {'num_ssms': 97, 'num_cnvs': 8, 'cellular_prevalence': [0.046772500000000002]} actual clone: {'num_ssms': 618, 'num_cnvs': 0, 'cellular_prevalence': [0.0019817099999999998]}
25 New clonal node: {'num_ssms': 715, 'num_cnvs': 8, 'cellular_prevalence': [0.0080582227692307679]}
121 Superclone: {'num_ssms': 129, 'num_cnvs': 8, 'cellular_prevalence': [0.018942199999999999]} actual clone: {'num_ssms': 586, 'num_cnvs': 0, 'cellular_prevalence': [0.0039054599999999999]}
121 New clonal node: {'num_ssms': 715, 'num_cnvs': 8, 'cellular_prevalence': [0.0066183823216783219]}
123 Superclone: {'num_ssms': 47, 'num_cnvs': 7, 'cellular_prevalence': [0.077607400000000007]} actual clone: {'num_ssms': 668, 'num_cnvs': 1, 'cellular_prevalence': [0.022573599999999999]}
123 New clonal node: {'num_ssms': 715, 'num_cnvs': 8, 'cellular_prevalence': [0.026191206433566431]}
Traceback (most recent call last):
  File "/data1/software/phylowgs-master/write_results.py", line 41, in <module>
    main()
  File "/data1/software/phylowgs-master/write_results.py", line 32, in main
    munger.remove_superclones()
  File "/data1/software/phylowgs-master/pwgsresults/result_munger.py", line 29, in remove_superclones
    assert len(structure[root_idx]) > 0
AssertionError

Any Idea why this is happening? It has worked for other samples perfectly so far. 

Best,
David

**Comment by jwintersinger** [comment]
Hi David,

Your cellular prevalences seem extremely low -- should your clonal node actually have only a CP of 0.078?

Can you send us your data, please? We'll try to replicate the issue on our end.

Thanks!
