### ISSUE TITLE
Assert error when creating ssm_data.txt 

### ISSUE THREAD

**Issue by pspealman** [morrislab/phylowgs#69]
[sample1_head.vcf.txt](https://github.com/morrislab/phylowgs/files/1435773/sample1_head.vcf.txt)
I've encountered a problem while trying to generate the ssm_data.txt file using a .vcf file generated using GATK's HaplotypeCaller on haploid yeast data.

Using the attached file ('sample1_head.vcf), and the command:
`python ../phylowgs/parser/create_phylowgs_inputs.py --vcf-type sample1=sanger sample1=sample1_head.vcf`

Results in the following error:
`Traceback (most recent call last):
  File "../phylowgs/parser/create_phylowgs_inputs.py", line 1354, in <module>
    main()
  File "../phylowgs/parser/create_phylowgs_inputs.py", line 1299, in main
    variant_ids, ref_read_counts, total_read_counts = parse_variants(samples, vcf_files, vcf_types, args.tumor_sample, args.missing_variant_confidence)
  File "../phylowgs/parser/create_phylowgs_inputs.py", line 1200, in parse_variants
    total_read_counts = impute_missing_total_reads(total_read_counts, missing_variant_confidence)
  File "../phylowgs/parser/create_phylowgs_inputs.py", line 1109, in impute_missing_total_reads
    assert np.sum(sample_means <= 0) == np.sum(np.isnan(sample_means)) == 0
AssertionError`

I feel like I'm missing something obvious. Any help or direction would be greatly appreciated.

**Comment by jwintersinger** [comment]
Hi Pieter,

Please let me know via e-mail if you have any further issues like this. Thanks! :)
