### ISSUE TITLE
CNV input?

### ISSUE THREAD

**Issue by yuchaojiang** [morrislab/phylowgs#7]
Hello,

I am a grad student at UPenn and am trying to use your PhyloWGS software to deconvolute clonal history using both SSMs and CNVs as input. I think your paper is very well written but I have a question about the CNV input for your software.

In your paper, it said that

We assume that a CNV algorithm has already been applied to the seqeucning data and that this algorithm provides estimates of copy number C and population frequency phi_i for each CNV i.
Although PhyloWGS requires the breakdown of C inot Cm and Cp under these conditions, we do not require the SSM to be phased, as many cannot be, and instead consider both possibilities when computing the likelihood.

And I believe I need to use C_i (total copy number with or without breakdown) and phi_i as input for your program. However, in your software webpage, it said that

cnv_data.txt: Note that if you are running without any CNVs, this file should be empty. You can create the empty file via the command touch cnv_data.txt.
•	cnv: identifier for each CNV. Identifiers must start at c0 and increment, so the first data row will have c0, the second row c1, and so forth.
•	a: number of reference reads covering the CNV.
•	d: total number of reads covering the CNV. This will be affected by factors such as total copy number at the locus, sequencing depth, and the size of the chromosomal region spanned by the CNV.
•	ssms: SSMs that overlap with this CNV. Each entry is a comma-separated triplet consisting of SSM ID, maternal copy number, and paternal copy number. These triplets are separated by semicolons.
 

Is the numeric value d the total read depth at each CNV? What about the value for a? Also, where does the total copy number and the proportion phi come into play? Also, for the comma separated copy number for each affected SNP, do they have to be whole numbers? I feel that due to heterogeneity issues they can't be integer values and also it seems hard to get them directly (which according to your paper you said that PhyloWGS doesn't require phasing).

Thanks!

Best,
Yuchao

**Comment by jwintersinger** [comment]
Hi Yuchao,
We have a parser that automatically generates these values now. The README contains instructions on how to run it. Please let us know if you have further questions.
