### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by heroapoorva** [morrislab/phylowgs#70]
So I have recently installed the dependencies i.e. followed the following instructions from README.md
1. Install dependencies.

  * Install Python 2 versions of NumPy (www.numpy.org) and SciPy (www.scipy.org).
  * Install Python 2 version of ETE2 (e.g.: `pip2 install --user ete2`).
  * Install GSL (http://www.gnu.org/software/gsl/).

2. Compile the C++ file.

        g++ -o mh.o -O3 mh.cpp  util.cpp `gsl-config --cflags --libs`

Till this point everything went fine.
While trying to run the program as given in the README.MD file, I got the following error:-
[2017-11-07 01:19:57.905274] Starting MCMC run...
[2017-11-07 01:19:57.907190] -1000
/home/firefistace/Glasgow/Project/phylowgs-master/mh.o: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "evolve.py", line 348, in run
    tmp_dir=args.tmp_dir
  File "evolve.py", line 124, in start_new_run
    do_mcmc(state_manager, backup_manager, safe_to_exit, run_succeeded, config, state, tree_writer, codes, n_ssms, n_cnvs, NTPS, tmp_dir)
  File "evolve.py", line 195, in do_mcmc
    config['tmp_dir']
  File "/home/firefistace/Glasgow/Project/phylowgs-master/params.py", line 61, in metropolis
    sp.check_call(['%s/mh.o' % script_dir, MH_ITR, MH_STD, N_SSM_DATA, N_CNV_DATA, NNODES, TREE_HEIGHT, FNAME_SSM_DATA, FNAME_CNV_DATA, FNAME_C_TREE, FNAME_C_DATA_STATES, FNAME_C_PARAMS,FNAME_C_MH_ARATIO, NTPS])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/home/firefistace/Glasgow/Project/phylowgs-master/mh.o', '5000', '100', '11', '1', '4', '3', 'ssm_data.txt', 'cnv_data.txt', '/tmp/pwgsdataexchange.fkfG5I/c_tree.txt', '/tmp/pwgsdataexchange.fkfG5I/c_data_states.txt', '/tmp/pwgsdataexchange.fkfG5I/c_params.txt', '/tmp/pwgsdataexchange.fkfG5I/c_mh_ar.txt', '5']' returned non-zero exit status 127

[2017-11-07 01:19:57.965553] Run failed.

Can someone please tell me what has gone wrong, I really don't understand the code.

**Comment by AmitDeshwar** [comment]
Hi,

Thanks for your interest in PhyloWGS!
I would guess that there's some problem with your input file.  Can you
provide a sample input file?

Amit

**Comment by heroapoorva** [comment]
The command I ran was (as given in README.md)
 
python2 evolve.py ssm_data.txt cnv_data.txt

ssm_data.txt:-
id	gene	a	d	mu_r	mu_v
s0	a	66023,50883,62757,36056,58777	126755,100469,121941,71263,115417	0.999	0.5
s1	b	71532,50933,64719,52048,83311	135031,97485,120826,101788,157737	0.999	0.5
s2	c	93057,61406,72640,61648,54961	106716,83179,83799,86440,84607	0.999	0.5
s3	GOLGA7B	31531,40281,18089,34256,36473	72221,84463,37410,73050,76869	0.999	0.5
s4	KHNYN	94954,74636,67529,42328,59678	116386,106518,83271,66152,94465	0.999	0.5
s5	NPHP4	9653,2300,4506,3559,3695	112775,79087,84707,92076,95849	0.999	0.5
s6	NPM1	9072,2953,4140,5150,5270	127079,112052,86626,137055,185970	0.999	0.5
s7	OLFM2	36288,28055,26648,35692,26492	74007,58150,56286,76579,54844	0.999	0.5
s8	PYHIN1	75935,106216,153378,115054,112006	76826,111139,155389,123305,119960	0.999	0.5
s9	RHCG	28543,31070,57616,34454,40929	51929,64677,116465,68393,79788	0.999	0.5
s10	SMC1A	54447,39896,60454,63950,48658	82781,73370,92894,120384,89511	0.999	0.5

cnv_data.txt:-
cnv	a	d	ssms	physical_cnvs
c0	66023,50883,62757,36056,58777	126755,100469,121941,71263,115417	s2,1,2;s4,0,1	chrom=1,start=1234,end=5678,major_cn=2,minor_cn=1,cell_prev=0.8;chrom=X,start=15,end=10000,major_cn=2,minor_cn=0,cell_prev=0.8;chrom=22,start=123,end=456,major_cn=1,minor_cn=0,cell_prev=0.8

Hope that helps

**Comment by AmitDeshwar** [comment]
Ah, I didn't read your original error message closely enough.
It looks like phyloWGS can't find your GSL.  Are you sure you installed it?
Can you include the output of:

gsl-config --cflags --libs

**Comment by heroapoorva** [comment]
Hi,
So in the terminal I went to the my directory where I kept all the phylowgs files, and wrote
gsl-config --cflags --libs

Output:-
-I/home/firefistace/anaconda3/include
-L/home/firefistace/anaconda3/lib -lgsl -lgslcblas -lm

I use LMDE2 btw. I use anaconda for jupyter notebook.

**Comment by heroapoorva** [comment]
As you said, there was some problem with the GSL. 
I installed the GSL again and it worked.

Thanks
