### ISSUE TITLE
Output of clonalFrequencies is empty

### ISSUE THREAD

**Issue by juvejones** [morrislab/phylowgs#72]
Hi -

By using the testing example provided in the package, I was able to generate successfully the tree.zip file, as well as a file named  'clonalFrequencies'. I assume this is where you'd get output about cellularity of individual mutation, but the output only contains one line of header (which is the ssm), without any actually frequency number below:

22_29622386, 7_1540017, 14_52520719, 10_50010692, 20_46281615, 15_75981976, 13_114786872, 9_92995183, 6_8435627, 7_73117350

I check evolve.py and apparently it is not writing out the numbers:

 #save clonal frequencies
        freq = dict([(g,[] )for g in state['glist']])
        glist = array(freq.keys(),str)
        glist.shape=(1,len(glist))
        ###
        print(freq)
        ###
        savetxt(state['clonal_freqs_file'] ,vstack((glist, array([freq[g] for g in freq.keys()]).T)), fmt='%s', delimiter=', ')

Is there a fix for this? Thank you!

**Comment by jwintersinger** [comment]
Hi @juvejones,

Sorry -- `clonalFrequencies` is an artifact of a previous version. Please run `write_results.py` and then view your results in a web browser through Witness, as described in steps 4 and 5 of the README (https://github.com/morrislab/phylowgs/blob/master/README.md). This will give you a visual representation of the tree and frequencies of populations.

Actually getting the mutation assignment to nodes requires digging into the JSON output. We'll be happy to help you with that if necessary.

Thanks!

**Comment by juvejones** [comment]
Thanks!
In my case I just need the clonality of individual mutation so I tried to extract mutation assignment from trees.zip file. It seems to work correctly. I can create a pull request for that piece of code if you think it helps.

**Comment by jwintersinger** [comment]
I'm glad that was helpful! We're currently working on an alternative means of summarizing and reporting clonality output, but thank you for your offer of opening a PR. :)
