### ISSUE TITLE
Improved documentation for output

### ISSUE THREAD

**Issue by jounikuj** [morrislab/phylowgs#79]
Hi, I have used PhyloWGS for my targeted sequencing data and received very interesting results with it so far - so thank you for a great tool! So far I have used the "best tree" as described in https://github.com/morrislab/phylowgs/issues/61 as I don't fully understand how to interpret the output results of PhyloWGS. The documentation of the output seems to be more or less inadequate in this case. I would be more than happy if you could clarify what following abbreviations in the output mean;

nlgLH, seems to be natural logarithm of the likelihood?
LI = ?
BI = ?

Thank you in advance!
-Jouni

**Comment by jwintersinger** [comment]
Hi! We just wrote a [README that addresses your questions](https://github.com/morrislab/phylowgs/blob/gmm-tree-clustering/witness/README.md). Let us know if we can clarify anything!
