### ISSUE TITLE
Preparing multi-sample data

### ISSUE THREAD

**Issue by ikramu** [morrislab/phylowgs#8]
Hi,

I want to use PhyloWGS for reconstructing tumor phylogeny using multiple samples from a patient. These include (multiple) samples from primary tumor and/or matastasis. 

Looking at the test data (ssm_data.txt), for each specific variant (row), the number of reference-alleles (a) and total reads (d) for all the five samples, right? Since usually in such data, there are some sites not shared by all the samples (i.e., for all samples for that particular site, we don't have the variant call info thus no data for some "a" and "d"), I was wondering how we may include such information in the ssm_data.txt file.

As an example, consider the following toy ssm_data.txt data consisting of four variant calls for three samples (say 2 primary and 1 matastasis). 
id      gene    a       d       mu_r    mu_v
s0      2_234577       83,52,56   155,169,141       0.999   0.5
s1      7_234577       52,0,69   135,95,826       0.999   0.5
s2      11_234577       57,96,0   82,179,99  0.999   0.5
s3      19_234577       38,46,10   92,79,91  0.999   0.5

In the above case, I want to tell PhyloWGS that sample2 have no (or zero) variant-calls for s1 (or 7_234577). Similarly sample3 have no (or zero) variant calls for s2 (or 11_234577). Is it right representation for PhyloWGS? In case it isn't and PhyloWGS supports such a representation, can you please guide me on the format.

Thanks,
Ikram

**Comment by jwintersinger** [comment]
Hi Ikram,

Listing variants that don't appear in all samples simply requires that you set `a = d` (meaning there are no variant reads in the given sample). `d`, then, should be set to the read depth for the given sample, which you could potentially take as the mean `d` value for all variants that *were* called in the sample.

We will soon be adding multisample support to our parser. May I ask if you have discrete VCF files for each sample, or if you have a single multi-sample VCF?

Thanks!

Jeff

**Comment by ikramu** [comment]
Hi Jeff,

Thanks for the explanation. I think I understood but just for clarification, in above example, we will set "a" and "d"=(52+96+46)/3=64 for sample2 in s1. Similary, we will set a=d=(56+69+10)/3=45 for sample3 in s2, Right?

Regarding input files, I have, for each sample, its mutect-based variant call file from which I extract reference calls "t_ref_count" for a, and "t_ref_count + t_alt_count" for d. 

Thanks again!
Ikram

**Comment by AmitDeshwar** [comment]
Hi Ikram

Do you have the BAM files for these samples?
I ask because instead of using the mean from the other samples it is better
if you can just get the actual read depth at that position for that sample.
Also it can be useful to check to see if there were actually a small number
of reads supporting the variant (but not enough for Mutect to call).

Amit

**Comment by ikramu** [comment]
Hi Amit,

Great idea! I think one of our project member at the other lab may have the BAM files. In case I get those, I hope it will make the results even more realistic. 
Jeff idea is great as well as, otherwise, I can reconstruct evolutionary trees as well.

Thanks,
Ikram
