### ISSUE TITLE
Battenberg input

### ISSUE THREAD

**Issue by mauroraptor86** [morrislab/phylowgs#81]
Hello,

I am sorry if this question may sound stupid, but which output file from Battenberg (since there are many) should be used for the phylowgs parser?

**Comment by jwintersinger** [comment]
Hi! You need the Battenberg file that has the following columns:

* chr
* startpos
* endpos
* BAF
* pval
* LogR
* ntot
* nMaj1_A
* nMin1_A
* frac1_A
* nMaj2_A
* nMin2_A
* frac2_A
* SDfrac_A
* SDfrac_A_BS
* frac1_A_0.025
* frac1_A_0.975
* nMaj1_B
* nMin1_B
* frac1_B
* nMaj2_B
* nMin2_B
* frac2_B
* SDfrac_B
* SDfrac_B_BS
* frac1_B_0.025
* frac1_B_0.975
* ...

Please let us know if this helps!

**Comment by mauroraptor86** [comment]
Ok, perfect. It is the [Tumor_sample]_subcones.txt file.

In the parser guide there is:

> Please note that your listing of CNVs must list regions of normal copy number as well.

Battenberg output lists only the region with a not normal copy number...

**Comment by mauroraptor86** [comment]
Oh I see now the after CNV parsing the resulting files have also regions with a copy number of 2. Are these the regions of normal copy number, aren't they?
Oh, and is it normal that some regions appear more than once? 

chromosome	start	end	copy_number	minor_cn	major_cn	cellular_prevalence
1	768253	149892872	1	0	1	0.341104661059
1	768253	149892872	2	1	1	0.568895338941
1	149905279	249223485	2	1	1	0.236983526525
1	149905279	249223485	3	1	2	0.673016473475

**Comment by Rashesh7** [comment]
Hi @mauroraptor86 ,
I also had the same question. Did you have to post-process the Battenberg file in any way to make it compatible for phyloWGS input? 

You help is much appreciated.
