### ISSUE TITLE
clonal_frequencies output

### ISSUE THREAD

**Issue by ikramu** [morrislab/phylowgs#9]
Hi,

While running PhyloWGS on SSM data (and empty CNV file), the program outputs clonalFrequencies file which, though have the 'gene' names in the header, doesn't have the clonal frequencies. I tried changing the name for the file (to mymy_clonal_freq.csv) and can see the file created but again without the frequencies' values.

Here is the command I used to run the program
python2 evolve.py -f my_clonal_freq.csv -s 1000 -i 2000 n20.ssm empty.cnv
I can see the my_clonal_freq.csv file but without the values (headers are present though)

I also tried with default run as follows.
python2 evolve.py n20.ssm empty.cnv
but the clonalFrequencies doesn't contains any values either. Please note that other output files, like top_trees/ or trees.zip, are present after the run; its just the clonal frequencies' file that is without the values.

One other question! Can we generate partial order plot in PhyloWGS (like we do in PhyloSub)? If yes, can we set the parameters in the program there to ignore the links in the plot below certain posterior probability?

Thanks for the assistance! 
Ikram

**Comment by jwintersinger** [comment]
Hi Ikram,
Looks like no one picked up your issue. Do you still need assistance?

**Comment by ShadrielleE** [comment]
@jwintersinger 

I actually have this same issue now. Could we reopen this?

**Comment by jwintersinger** [comment]
Hi Shadrielle,

The best way to get clonal frequencies is to use PhyloWGS WItness. It will list the cellular prevalences for each population.

**Comment by ShadrielleE** [comment]
Hi Jeff,

There are Trees vs. Cellular Prevalence barplots, but I would like cellular prevalence attached to each SSM. Sort of like the "Number of Variants vs. VAF" barplot. I thought the clonalFrequencies output file would have given this.

**Comment by jwintersinger** [comment]
Hi Shad,

The best way to get at this information is to use our [SMC-Het code](https://github.com/morrislab/smchet-challenge/tree/master/create-smchet-report). It runs on the same JSON files that Witness uses. After running `write_report.py`, `2A.txt` will list assignment of mutations to clusters, while `1C.txt` will give you the cellular prevalence ("phi") of the cluster. The code establishes estimates for these values from all your trees sampled, which is a better representation than any individual tree you will see in WItness.

The only problem is that the code doesn't work well on multi-sample data. Is your data multi-sample?

**Comment by ShadrielleE** [comment]
Yes, my data is multi-sample. Can I assume that the output of 2A corresponds line-by-line to the ssm.txt file? It also seems that the cellular prevalence is calculated by averaging across the samples -- this is probably what you meant by the code not working well on multi-samples. Thanks for mentioning that.

Also, thanks for the quick replies!

**Comment by jwintersinger** [comment]
You're correct -- the first line of `2A.txt` corresponds to the SSM `s0`, the second line to `s1`, and so forth.

You're right about the multi-samples -- cellular prevalences are obtained just by taking the mean across samples. This was just a hack I put it to get the code working on single-sample cases. I'm revisiting the tools surrounding PhyloWGS to make them work properly with multiple samples now. The first step is to get the parser working with multi-sample SSMs and CNVs; after I do that, I will modify the SMC-Het code to properly account for multi-samples.

We have no plans to fix the clonalFrequencies file. In fact, we should probably modify the code to no longer write the file. Visualization of the data is best done via Witness, while questions it doesn't answer can be addressed via the JSON output (or the SMC-Het results generated from it, which should account for the distribution of values across all trees we sample).

**Comment by ShadrielleE** [comment]
Sounds good. I look forward to the parser working with multi-sample SSMs and CNVs. Thanks for the help
