### ISSUE TITLE
TitanCNA clustering solution selection

### ISSUE THREAD

**Issue by peterpdu** [morrislab/phylowgs#96]
I was wondering how sensitive phylowgs is to changes in the clustering solution selection of TitanCNA output. For instance, if I choose a 4 cluster solution versus a 3 cluster solution from Titan as cnv input to phylowgs (and also supply ssm data), will the resulting phylowgs solutions be very different?

**Comment by jwintersinger** [comment]
Hi @peterpdu,

PhyloWGS treats CNAs as pseudo-SSMs. As CNAs are supported by much larger genomic regions than SSMs, they will have a greater effect in driving the cellular prevalence of the clusters PhyloWGS assigns them to. I'm not terribly familiar with TITAN, but if the four-cluster solution and the three-cluster solution report substantially different cellular prevalences for their segments, these will likely push PhyloWGS to create different clusters -- e.g., if the four cluster solution has segments with CPs [0.9 0.7 0.4 0.1], these are likely different enough that it will push PhyloWGS to create four clusters around these CPs, with SSMs potentially driving the creation of additional clusters or being assigned to CNA-driven clusters.

Does that make sense?

**Comment by peterpdu** [comment]
Thanks, that's very helpful!
